# Generated by Django 5.1.2 on 2025-01-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCertifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_ps_no', models.IntegerField()),
                ('employee_designation', models.CharField(max_length=50)),
                ('certification_name', models.CharField(max_length=50)),
                ('exam_date', models.DateField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('certification_status', models.CharField(max_length=50)),
                ('uploaded_certificate', models.FileField(null=True, upload_to='')),
                ('voucher_code', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'employeecertifications',
            },
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
