# Generated by Django 5.1.4 on 2025-02-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employeecertifications_delete_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecertifications',
            name='employee_designation',
        ),
    ]
