# Generated by Django 5.1.4 on 2025-02-03 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employeecertifications_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecertifications',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='employeecertifications',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
