# Generated by Django 5.1.4 on 2025-02-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_employeecertifications_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertifications',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeecertifications',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
